var m=Object.defineProperty;var y=(e,t,s)=>t in e?m(e,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):e[t]=s;var l=(e,t,s)=>(y(e,typeof t!="symbol"?t+"":t,s),s);import{a as i}from"./assets/vendor-a61d8330.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();class u{constructor(t){l(this,"baseUrl","https://food-boutique.b.goit.study/api/");this.endPoint=t}async fetchBreeds(){try{const t=await i.get(`${this.baseUrl}${this.endPoint}`);return console.log(t.data),t.data}catch(t){console.error("Error:",t.message)}}}const g=document.querySelector(".search-form"),h=document.querySelector(".input-search");document.querySelector(".button-search");const d=document.querySelector(".filters-result");let n={};const S=()=>{const e=`<div class="error">
    <p class="title-error">
        Nothing was found for the selected <span><a class="a-title-error" href="">filters...</a></span>
    </p>
    <p class="p-error">
        Try adjusting your search parameters or browse our range by other criteria to find the perfect product for you.
    </p>
</div>`;d.innerHTML=e};async function f(){try{const e=localStorage.getItem("products-home-page-filters");if(e)n=JSON.parse(e);else{const t="products";n=await new u(t).fetchBreeds(),localStorage.setItem("products-home-page-filters",JSON.stringify(n))}}catch(e){console.error("Error:",e.message)}console.log(n)}f();g.addEventListener("submit",async e=>{e.preventDefault();const t=h.value.trim();if(!t)f(),d.innerHTML="";else{const s=`products?keyword=${t}`;n=await new u(s).fetchBreeds(),n.totalPages===0&&S()}console.log(n.totalPages)});document.addEventListener("DOMContentLoaded",function(){const e=b();e?p(e):P()});function P(){i.get("https://food-boutique.b.goit.study/api/products/popular?limit=5").then(e=>{p(e.data),q(e.data)}).catch(e=>console.error("Error:",e))}function q(e){localStorage.setItem("popularProducts",JSON.stringify(e))}function b(){const e=localStorage.getItem("popularProducts");return e?JSON.parse(e):null}function p(e){const t=document.querySelector(".products-container"),s=document.querySelector(".product-template");e.forEach(c=>{const r=s.cloneNode(!0);r.style.display="flex",r.querySelector(".product-image").src=c.img,r.querySelector(".product-name").textContent=c.name,r.querySelector(".category-value").textContent=c.category.replace("_"," "),r.querySelector(".size-value").textContent=c.size,r.querySelector(".popularity-value").textContent=c.popularity;const o=r.querySelector(".add-to-cart-btn");o.onclick=function(){v(c._id)},t.appendChild(r)})}function v(e){console.log("Додавання продукту в кошик:",e)}
//# sourceMappingURL=commonHelpers.js.map
